### PR TITLE
step: train and test one model

### PR DESCRIPTION
**Pull request by masonlr**
This pull request is a review of #63

### CODE REVIEW

**Comment by masonlr** [comment]
Have added `MODEL_0.zip` to the code base (previously this was ignored by the `.gitignore` files).

**Comment by masonlr** [comment]
@jia-chenhua there is now a call to `env.check_reset()` in the test file `test_environment_reset.py`. Can you let me know what value this should return? At the moment, I'm getting:

```
$ ./test_environment_reset.py
...
Final results from 1st run:  -1116900.6534423828
Final results from 2nd run:  -1116900.6534423828
...
reset_diff=24534.571500916143
```

**Comment by jia-chenhua** [comment]
> 



> @jia-chenhua there is now a call to `env.check_reset()` in the test file `test_environment_reset.py`. Can you let me know what value this should return? At the moment, I'm getting:
> 
> ```
> $ ./test_environment_reset.py
> ...
> Final results from 1st run:  -1116900.6534423828
> Final results from 2nd run:  -1116900.6534423828
> ...
> reset_diff=24534.571500916143
> ```

The `env.check_reset()` should be run right after an `env.reset()` and it should give 0 if `env.reset()` is correct.

**Comment by masonlr** [comment]
If I add that explicit call to `env.reset()` then I can reproduce the zero diff:

```
$ ./test_environment_reset.py
...
Final results from 1st run:  -1116900.6534423828
Final results from 2nd run:  -1116900.6534423828
...
reset_diff=0.0
```

**Comment by masonlr** [comment]
At this stage uncommenting the lines as per https://github.com/rangl-labs/netzerotc/issues/63#issuecomment-975950934 is still giving

```
$ ./test_environment_reset.py
...
Final results from 1st run:  -1118805.9122314453
Final results from 2nd run:  -1118805.9122314453
...
reset_diff=0.0
```


i.e. the results change, but the reset diff is still 0.0.

@jia-chenhua do you expect the results to change if those lines are uncommented?

**Comment by masonlr** [comment]
This difference indicates that the env has changed. It indicates that reset is working correctly though.

**Comment by jia-chenhua** [comment]
> At this stage uncommenting the lines as per [#63 (comment)](https://github.com/rangl-labs/netzerotc/issues/63#issuecomment-975950934) is still giving
> 
> ```
> $ ./test_environment_reset.py
> ...
> Final results from 1st run:  -1118805.9122314453
> Final results from 2nd run:  -1118805.9122314453
> ...
> reset_diff=0.0
> ```
> 
> i.e. the results change, but the reset diff is still 0.0.
> 
> @jia-chenhua do you expect the results to change if those lines are uncommented?

The 1e-4 difference is between `-1118805.9122314453` and `-1116900.6534423828` as you obtained...

**Pull request merged**
